### 1. Test Valid Ingestion Payload
POST http://localhost:8000/audit/events
Content-Type: application/json

{
  "event_id": "evt_98765",
  "source": "payment-gateway",
  "timestamp": "2026-08-08T17:00:00Z",
  "encrypted_payload": "U2FsdGVkX1+xyz123abc=="
}

### 2. Test Invalid Payload (Triggers Zod 400 Bad Request)
POST http://localhost:8000/audit/events
Content-Type: application/json

{
  "event_id": "evt_98765",
  "source": "payment-gateway"
}

### 3. Check K8s Readiness Probe
GET http://localhost:8000/health/ready

### 4. Check K8s Liveness Probe
GET http://localhost:8000/health/live

### 5. Test Decryption Worker (Success Test)
POST http://localhost:8000/audit/events
Content-Type: application/json

{
  "event_id": "evt_00002",
  "source": "auth-service",
  "timestamp": "2026-08-11T18:32:00Z",
  "encrypted_payload": "6717d48028bbc592beeed002:e9a5af7227a141ff310061d8ec83312ad5f2207bb54ace79f6ba51:ccad86df0191883af64c8fbabd930273"
}

### 6. Test E2E inside K8s
POST http://localhost:8000/audit/events
Content-Type: application/json

{
  "event_id": "evt_k8s_001",
  "source": "payment-service",
  "timestamp": "2026-08-13T12:00:00Z",
  "encrypted_payload": "PASTE_YOUR_ENCRYPTED_PAYLOAD_HERE"
}