apiVersion: apps/v1
kind: Deployment
metadata:
  name: cipherflow-worker
  labels:
    app: cipherflow-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cipherflow-worker
  template:
    metadata:
      labels:
        app: cipherflow-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: worker
        image: cipherflow-worker:1.0
        imagePullPolicy: Never
        # NOTE: Hardcoding secrets here is temporary. 
        # We will lock this down with K8s Secrets on Day 8.
        env:
        - name: REDIS_HOST
          value: "redis-svc"
        - name: DB_HOST
          value: "postgres-svc"
        - name: DB_NAME
          value: "cipherflow"
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: cipherflow-secrets
              key: encryption-key
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cipherflow-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cipherflow-secrets
              key: db-password